### ISSUE TITLE
error when run process_function.py

### ISSUE THREAD

**Issue by w5688414** [BINE022/EEGPT#9]
I found an error when I run proces_function.py, it seems the mat files missing.

```
- Cutoff at 38.00 Hz: -6.02 dB

Traceback (most recent call last):
  File "/media/data/miniconda3/envs/py39/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 39, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: '../../datasets/downstream/Raw_data/BCICIV_2a_gdf/A01E.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/data/projects/A30105-31172/EEGPT-main/downstream/Data_process/process_function.py", line 125, in <module>
    Load_BCIC_2a_raw_data()
  File "/media/data/projects/A30105-31172/EEGPT-main/downstream/Data_process/process_function.py", line 49, in Load_BCIC_2a_raw_data
    data = data_loader.get_epochs(tmin=tmin, tmax=tmax,bandpass = bandpass,resample = resample)
  File "/media/data/projects/A30105-31172/EEGPT-main/downstream/Data_process/LoadData.py", line 103, in get_epochs
    label_info  = sio.loadmat(os.path.join(self.eeg_file_path,self.label_name))
  File "/media/data/miniconda3/envs/py39/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/media/data/miniconda3/envs/py39/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/media/data/miniconda3/envs/py39/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/media/data/miniconda3/envs/py39/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: '../../datasets/downstream/Raw_data/BCICIV_2a_gdf/A01E.mat'
```

where can i download mat files?  like: datasets/downstream/Raw_data/BCICIV_2b_gdf/B0905E.mat

the mat files are in this website?  but I didn't find out the mat zip files. https://www.bbci.de/competition/iv/download/index.html?agree=yes&submit=Submit

**Comment by w5688414** [comment]
where can I download the matfile, I only get access to the gdf files :

```
datasets/downstream/Raw_data/BCICIV_2a_gdf/A01E.gdf
datasets/downstream/Raw_data/BCICIV_2a_gdf/A01E.mat
...
datasets/downstream/Raw_data/BCICIV_2a_gdf/A09T.gdf
datasets/downstream/Raw_data/BCICIV_2a_gdf/A09T.mat
...
datasets/downstream/Raw_data/BCICIV_2b_gdf/B0905E.gdf
datasets/downstream/Raw_data/BCICIV_2b_gdf/B0905E.mat
```

**Comment by w5688414** [comment]
I found the labels, the problem solved. https://bbci.de/competition/iv/results/index.html#dataset2a
